version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5317:3000"

  db:
    user: root
    container_name: postgres
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 1234
    ports:
      - 5439:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data


  pgadmin:
    user: root
    container_name: pgadmin
    image: dpage/pgadmin4:5.7
    environment:
      PGADMIN_DEFAULT_EMAIL: "habrpguser@habr.com"
      PGADMIN_DEFAULT_PASSWORD: "1234"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "5313:80"
    restart: unless-stopped

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "5314:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
